Add build instructions
SenegalLang/Senegal pull request #3
Opened 2020-11-09 08:16 UTC by Andy-Python-Programmer

This pull request adds the build instructions for both windows and unix like operating systems.

2020-11-10 01:07 UTC, Calamity210 commented
This is assuming everyone is using cmake. Both the gcc and mingw installs are redundant, please add steps for make as well

2020-11-10 01:08 UTC, Calamity210 requested changes
Take a look at the comment

2020-11-10 01:27 UTC, Andy-Python-Programmer commented
@Calamity210 I think that `mingw` install can be important as the build will not work in windows build tools using cl.

2020-11-10 01:29 UTC, Calamity210 commented
Afaik mingw doesnt ship cmake

2020-11-10 03:38 UTC, Andy-Python-Programmer commented
@Calamity210 I know but cmake will need mingw to work.

2020-11-23 06:00 UTC, Andy-Python-Programmer commented
Added build instructions for using `make` @Calamity210

2020-12-13 06:21 UTC, MrBirb commented on README.md
> +1. Make you have installed the dependencies:
nit: Make sure*

2020-12-13 21:39 UTC, Calamity210 commented
@Andy-Python-Programmer im going to hold off on reviewing this as there are going to be some changes in the build process soon

2020-12-14 19:33 UTC, Calamity210 commented
@Andy-Python-Programmer please take a look at 022006a

2020-12-16 22:48 UTC, Calamity210 requested changes

2020-12-25 16:40 UTC, Calamity210 commented
Closing since #14 makes it simpler to build and run senegal

2020-12-25 16:40 UTC, closed without merging